// See README.md for license details.

package dirv

import chisel3._

/**
  * This provides an alternate way to run tests, by executing then as a main
  * From sbt (Note: the test: prefix is because this main is under the test package hierarchy):
  * {{{
  * test:runMain dirv.DirvMain
  * }}}
  * To see all command line options use:
  * {{{
  * test:runMain dirv.DirvMain --help
  * }}}
  * To run with verilator:
  * {{{
  * test:runMain dirv.DirvMain --backend-name verilator
  * }}}
  * To run with verilator from your terminal shell use:
  * {{{
  * sbt 'test:runMain dirv.DirvMain --backend-name verilator'
  * }}}
  */
object DirvMain extends App {
  implicit val cfg = Config()
  iotesters.Driver.execute(args, () => new SimDtm) {
    c => new DirvUnitTester(c)
  }
}

/**
  * This provides a way to run the firrtl-interpreter REPL (or shell)
  * on the lowered firrtl generated by your circuit. You will be placed
  * in an interactive shell. This can be very helpful as a debugging
  * technique. Type help to see a list of commands.
  *
  * To run from sbt
  * {{{
  * test:runMain dirv.DirvRepl
  * }}}
  * To run from sbt and see the half a zillion options try
  * {{{
  * test:runMain dirv.DirvRepl --help
  * }}}
  */
object DirvRepl extends App {
  implicit val cfg = Config()
  iotesters.Driver.executeFirrtlRepl(args, () => new SimDtm)
}
